apiVersion: extensions.kubesphere.io/v1alpha1
kind: JSBundle
metadata:
  name: {{ include "frontend.fullname" . }}-js-bundle
spec:
  rawFrom:
    url: http://{{ include "frontend.fullname" . }}.{{ .Release.Namespace }}.svc
status:
  enabled: true
  link: /dist/{{ include "frontend.fullname" . }}/index.js
