apiVersion: v2
name: backend
description: Backend of employee plugin.
type: application
version: 0.0.1
appVersion: "0.0.1"
home: https://kubesphere.io
sources:
  - https://github.com/chenz24/console
annotations:
  extensions.kubesphere.io/foo: bar
