apiVersion: v2
name: frontend
description: Frontend of [[ .Name ]] extension.
type: application
version: 0.0.1
appVersion: "0.0.1"
home: https://kubesphere.io
sources:
  - https://github.com/kubesphere
annotations:
  extensions.kubesphere.io/foo: bar
